apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-campaign
  namespace: campaign
spec:
  selector:
    matchLabels:
      app: tg-campaign
  replicas: 1
  template:
    metadata:
      labels:
        app: tg-campaign
    spec:
      containers:
        - name: tg-campaign
          image: dopeteam/tg-campaign:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: REDIS_PASSWORD
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: KAFKA_HOST

            - name: S3_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: S3_SECRET_KEY
            - name: S3_REGION_STATIC
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: S3_REGION_STATIC
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: S3_BUCKET
            - name: S3_DIRECTORY_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: S3_DIRECTORY_IMAGE
            - name: S3_DIRECTORY_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: campaign-service-config
                  key: S3_DIRECTORY_PROFILE
