server:
  servlet:
    contextPath: /api/community
    session:
      cookie:
        path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-of-girls
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
    open-in-view: false
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  kafka:
    host: ${KAFKA_HOST}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus

aws:
  s3:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION_STATIC}
    bucket: ${S3_BUCKET}
    directory:
      image: ${S3_DIRECTORY_IMAGE}
      profile: ${S3_DIRECTORY_PROFILE}
