apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-community
  namespace: community
spec:
  selector:
    matchLabels:
      app: tg-community
  replicas: 2
  template:
    metadata:
      labels:
        app: tg-community
    spec:
      containers:
        - name: tg-community
          image: dopeteam/tg-community:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: KAKAO_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: KAKAO_REDIRECT_URI
            - name: KAKAO_API_URL_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: KAKAO_API_URL_TOKEN
            - name: KAKAO_API_URL_INFORMATION
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: KAKAO_API_URL_INFORMATION
            - name: S3_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: S3_SECRET_KEY
            - name: S3_REGION_STATIC
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: S3_REGION_STATIC
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: S3_BUCKET
            - name: S3_DIRECTORY_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: S3_DIRECTORY_IMAGE
            - name: S3_DIRECTORY_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: S3_DIRECTORY_PROFILE
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: community-service-config
                  key: REDIS_PASSWORD